a=[1 3 0;3 1 0;9 2 4];
% b=sort(a)   %hang
% c=sort(a,2) %lie
% d=sort(a,'descend')
% e=sort(a,2,'descend')
% f=[b c;d e]
% g=sum(a)
% h=sum(a,2)
% i=cumsum(a)
% j=cumsum(a,2)
% k=sum(sum(a))  %求出矩阵所有元素的和
% a=magic(3)
% b=prod(a)
% c=prod(a,2)
% d=cumprod(a)
% e=cumprod(a,2)
a=magic(3)
b=diff(a)
c=diff(a,2)
d=diff(a,1,1)
e=diff(a,1,2)